apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashu-ak-01
  labels:
    app: django-blog

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
    spec:
      containers:
      - name: ashu-ak-01
        image: ashuverma8321/ashu-docker:2
        ports:
        - containerPort: 8000