apiVersion: v1
kind: Service
metadata:
  name: ashu-ak-01

spec:
  type: NodePort
  selector:
    app: django-blog
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8000
      nodePort: 30001

      